---
title: "Cuentas Fiscales"
author: "Daniel Alvarez Perez"
output:
  html_document:
    toc: true
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd(getwd())
library(WDI)
library(plotly)
library(dplyr)
library(RColorBrewer)
library(htmlwidgets)
library(highcharter)
```

<style type="text/css">
h1 {color:#1a2451}
h2 {color:#ffbd4a}
h3 {color:#1a2451}
</style>

## Balanza comercial de bienes y servicios (% del PIB)


```{r include=FALSE}
BC <- data.frame(
WDI(country = c("AR","BO","BR","CL","CN","ES","FI","PE","PY","US","SV"),
    indicator = "NE.RSB.GNFS.ZS",
    start = 1990,
    end = 2019,
    extra = FALSE))
```

```{r echo=FALSE}
hchart(BC, "line", hcaes(x= year, y =NE.RSB.GNFS.ZS, group = country))%>% 
  hc_title(text="Balanza comercial de bienes y servicios")%>%
  hc_subtitle(text ="(% del PIB)")%>%
  hc_colors(c("skyblue","#336600","yellow","red","#660000","purple","#003366","#fffcc","#ccffcc","blue","#99ff99"))%>%
  hc_yAxis(title = list(text = "in $$$s"),
           opposite = FALSE)%>%  # Enable the legend
  hc_legend(enabled = TRUE)  

```

## Saldo en Cuenta Corriente (Balanza de Pagos)

```{r include=FALSE}
SCC <- data.frame(
WDI(country = c("AR","BO","BR","CL","CN","ES","FI","PE","PY","US","SV"),
    indicator = "BN.CAB.XOKA.CD",
    start = 1990,
    end = 2019,
    extra = FALSE))
```

```{r echo=FALSE}
hchart(SCC, "line", hcaes(x= year, y =BN.CAB.XOKA.CD, group = country))%>% 
  hc_title(text="Saldo en Cuenta Corriente")%>%
  hc_subtitle(text ="(Balanza de Pagos)")%>%
  hc_colors(c("skyblue","#336600","yellow","red","#660000","purple","#003366","#fffcc","#ccffcc","blue","#99ff99"))%>%
  hc_yAxis(title = list(text = "in $$$s"),
           opposite = FALSE)%>%  # Enable the legend
  hc_legend(enabled = TRUE)  

```


## Reservas Internacionales- incluyendo Oro

```{r include=FALSE}
reservas <- data.frame(
WDI(country = c("AR","BO","BR","CL","CN","ES","FI","PE","PY","US","SV"),
    indicator = "FI.RES.TOTL.CD",
    start = 1990,
    end = 2019,
    extra = FALSE))
```

```{r echo=FALSE}
hchart(reservas, "line", hcaes(x= year, y = FI.RES.TOTL.CD, group = country))%>% 
  hc_title(text="Total Reservas Internacionales")%>%
  hc_colors(c("skyblue","#336600","yellow","red","#660000","purple","#003366","#fffcc","#ccffcc","blue","#99ff99"))%>%
  hc_yAxis(title = list(text = "in $$$s"),
           opposite = FALSE)%>%  # Enable the legend
  hc_legend(enabled = TRUE)  

```