---
title: "Deuda Externa"
author: "Daniel Alvarez Perez"
output:
  html_document:
    toc: true
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd(getwd())
library(WDI)
library(plotly)
library(dplyr)
library(RColorBrewer)
library(htmlwidgets)
library(highcharter)
```

<style type="text/css">
h1 {color:#1a2451}
h2 {color:#ffbd4a}
h3 {color:#1a2451}
</style>

## Deuda Externa Total


```{r include=FALSE}
DEUDA <- data.frame(
WDI(country = c("AR","BO","BR","CL","CN","ES","FI","PE","PY","US","SV"),
    indicator = "DT.DOD.DECT.CD",
    start = 1990,
    end = 2019,
    extra = FALSE))
```

```{r echo=FALSE}
hchart(DEUDA, "line", hcaes(x= year, y =DT.DOD.DECT.CD, group = country))%>% 
  hc_title(text="Deuda Externa Total")%>%
  hc_subtitle(text ="Acumulación de toda la deuda externa del país ")%>%
  hc_colors(c("skyblue","#336600","yellow","red","#660000","purple","#003366","#fffcc","#ccffcc","blue","#99ff99"))%>%
  hc_yAxis(title = list(text = "in $$$s"),
           opposite = FALSE)%>%  # Enable the legend
  hc_legend(enabled = TRUE)  

```

## Deuda Externa (% del Ingreso Nacional Bruto)

```{r include=FALSE}
deuda_PIB <- data.frame(
WDI(country = c("AR","BO","BR","CL","CN","ES","FI","PE","PY","US","SV"),
    indicator = "DT.DOD.DECT.GN.ZS",
    start = 1990,
    end = 2019,
    extra = FALSE))
```


```{r echo=FALSE}
hchart(deuda_PIB, "line", hcaes(x= year, y = DT.DOD.DECT.GN.ZS, group = country))%>% 
  hc_title(text="Deuda Externa en relación a los Ingresos")%>%
  hc_subtitle(text ="Porcentaje del Ingreso Nacional Bruto ")%>%
  hc_colors(c("skyblue","#336600","yellow","red","#660000","purple","#003366","#fffcc","#ccffcc","blue","#99ff99"))%>%
  hc_yAxis(title = list(text = "in $$$s"),
           opposite = FALSE)%>%  # Enable the legend
  hc_legend(enabled = TRUE)  

```


## Deuda a corto plazo (% de las exportaciones de bienes, servicios e ingresos primario)

```{r include=FALSE}
deuda_cp <- data.frame(
WDI(country = c("AR","BO","BR","CL","CN","ES","FI","PE","PY","US","SV"),
    indicator = "DT.DOD.DSTC.XP.ZS",
    start = 1990,
    end = 2019,
    extra = FALSE))
```

```{r echo=FALSE}
hchart(deuda_cp, "line", hcaes(x= year, y =DT.DOD.DSTC.XP.ZS, group = country))%>% 
  hc_title(text="Deuda a corto plazo (% de las exportaciones de bienes, servicios e ingresos primario) ")%>%
  hc_colors(c("skyblue","#336600","yellow","red","#660000","purple","#003366","#fffcc","#ccffcc","blue","#99ff99"))%>%
  hc_yAxis(title = list(text = "in $$$s"),
           opposite = FALSE)%>%  # Enable the legend
  hc_legend(enabled = TRUE)  

```