<head>
  <meta charset="utf-8">
  <title>Reported Active Tuberculosis Cases in the United States, 1993-2013</title>
  <link rel="stylesheet" href="jquery-ui/jquery-ui.min.css">
  <script src="jquery-ui/external/jquery/jquery.js"></script>
  <script src="jquery-ui/jquery-ui.js"></script>
  <script>
  $(function() {
    $( "#tabs" ).tabs();
  });
  </script>
</head>

```{r setup, echo= FALSE, message=FALSE,warning= FALSE}
# Strings ain't factors
options(stringsAsFactors = FALSE)
# Load the required libraries
library(knitr)
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(quantmod)
library(highcharter)
# Set the default ggplot theme
theme_set(theme_bw())
# Set default chunk options
opts_chunk$set(echo = FALSE,
               results = 'asis',
               message = FALSE,
               warning = FALSE,
               error = TRUE)
# Read in the table
tbstats_raw <- read.delim("cdc_otis_extract.txt")
tbstats <- tbstats_raw %>% 
    filter(Notes == "") %>% 
    mutate(per.complete = as.numeric(gsub(x = Percent.of.Completion.of.Therapy.Within.One.Year.Among.Those.Eligible,
                               pattern = "%|Not Applicable",
                               replacement = ""))) %>% 
    select(-matches("Notes"), -ends_with(".Code"))
```






# JQUERY TABS (Otra forma de mostrar Datos)


<div id="tabs">
<ul>
<li><a href="#states">EJEMPLO</a></li>
<li><a href="#treatment">GRAFIVO ESTATICO</a></li>
</ul>
    


<div id="states">
  
## Reported Active TB Cases by State
  
```{r cases}
top_five <-
    tbstats %>% 
    filter(Year == 1993) %>% 
    arrange(desc(Count)) %>% 
    slice(1:5) %>% 
    select(State)
tbstats$top_five_state <- factor(tbstats$State, levels = c(top_five$State, "Other"))
tbstats$top_five_state[is.na(tbstats$top_five_state)] <- "Other"
tbstats %>% 
    group_by(Year, State) %>%
    summarise(n_cases = sum(Count), 
              top_five_state = unique(top_five_state)) %>% 
    ggplot(aes(x = Year, y = n_cases, group = State)) +
        geom_line(aes(color = top_five_state, size = top_five_state)) +
        scale_size_manual(values = c(rep(2, 5), 0.5)) + 
        scale_color_manual(values = c(brewer.pal(n = 5, "Paired"), "grey")) +
        labs(x = "Year Reported",
             y = "Number of Cases",
             color = "State",
             title = "Reported Active TB Cases in the United States") +
        expand_limits(y = 0)
```

  
  
  
</div>


<div id="treatment">

## Treatment Completion Within One Year for Eligible US TB Cases



```{r tx_completion}
tbstats %>% 
    group_by(Year) %>% 
    summarise(tx_completion = weighted.mean(per.complete, w = Count)) %>% 
    ggplot(aes(x = Year, y = tx_completion)) +
        geom_line(size = 2) +
        expand_limits(y = 0) +
        labs(x = "Year Reported",
             y = "Percent of Cases Completed",
             title = "Completion of Treatment within One Year for Eligible Cases")
```

</div>



</div>


